### ISSUE TITLE
Error extracting faces - COLAB

### ISSUE THREAD

**Issue by smithee77** [chervonij/DFL-Colab#40]
Hi, first thanks for your effort with DFL :)
In latest Colab notebook, when I try to extract faces , I get this error. Any clue?
Thanks in advance

Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/content/DeepFaceLab/core/leras/device.py", line 95, in _get_tf_devices_proc
    compute_cache_path = Path(os.environ['APPDATA']) / 'NVIDIA' / ('ComputeCache_ALL')
  File "/usr/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'APPDATA'

**Comment by protocolGITHUB** [comment]
iperov fixed it today.

**Comment by chervonij** [comment]
...
