### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.compat.v2

### ISSUE THREAD

**Issue by hargums** [chervonij/DFL-Colab#44]
im facing issue with DFL_Colab_1-0.ipynb (because im using amd in my physical pc so i choose DFL_Colab_1-0.ipynb in colab)

Using TensorFlow backend.
Error: No module named 'tensorflow.compat.v2'
Traceback (most recent call last):
  File "/content/DeepFaceLab/mainscripts/Trainer.py", line 52, in trainerThread
    device_args=device_args)
  File "/content/DeepFaceLab/models/ModelBase.py", line 142, in __init__
    nnlib.import_all(self.device_config)
  File "/content/DeepFaceLab/nnlib/nnlib.py", line 1613, in import_all
    nnlib.import_keras(device_config)
  File "/content/DeepFaceLab/nnlib/nnlib.py", line 229, in import_keras
    import keras as keras_
  File "/usr/local/lib/python3.7/dist-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/usr/local/lib/python3.7/dist-packages/keras/utils/__init__.py", line 27, in <module>
    from .multi_gpu_utils import multi_gpu_model
  File "/usr/local/lib/python3.7/dist-packages/keras/utils/multi_gpu_utils.py", line 7, in <module>
    from ..layers.merge import concatenate
  File "/usr/local/lib/python3.7/dist-packages/keras/layers/__init__.py", line 4, in <module>
    from ..engine.base_layer import Layer
  File "/usr/local/lib/python3.7/dist-packages/keras/engine/__init__.py", line 3, in <module>
    from .input_layer import Input
  File "/usr/local/lib/python3.7/dist-packages/keras/engine/input_layer.py", line 7, in <module>
    from .base_layer import Layer
  File "/usr/local/lib/python3.7/dist-packages/keras/engine/base_layer.py", line 12, in <module>
    from .. import initializers
  File "/usr/local/lib/python3.7/dist-packages/keras/initializers/__init__.py", line 17, in <module>
    import tensorflow.compat.v2 as tf
ModuleNotFoundError: No module named 'tensorflow.compat.v2'

please help

**Comment by hargums** [comment]
i already use this version of colabs for couple weeks, but i think it because new update from DFL so it stop working. please solution suggested for OpenCL user. manythanks

**Comment by chervonij** [comment]
@hargums 
First of all, DFL 1.0 — outdated. It has not been supported since release of version 2.0 and is there for nothing more than backward compatibility. Moreover. OpenCL version of DFL no longer exists since April. It was replaced by DirectX version. And it works with DFL 2.0

So, there is no reason to use DFL 1.0

**Comment by hargums** [comment]
@chervonij im using amd rx460 is it compatible with dfl 2.0 ? Thanks

**Comment by chervonij** [comment]
@hargums 
Just download DFL DirectX build and try. It works with AMD cards.
