### ISSUE TITLE
ModuleNotFoundError: No module named 'colorama'

### ISSUE THREAD

**Issue by Orchoidizer** [chervonij/DFL-Colab#45]
Does anybody know what is happening here. 
Started happening a few hours ago when trying to do most things

Traceback (most recent call last):
  File "/content/DeepFaceLab/main.py", line 6, in <module>
    from core.leras import nn
  File "/content/DeepFaceLab/core/leras/__init__.py", line 1, in <module>
    from .nn import nn
  File "/content/DeepFaceLab/core/leras/nn.py", line 26, in <module>
    from core.interact import interact as io
  File "/content/DeepFaceLab/core/interact/__init__.py", line 1, in <module>
    from .interact import interact
  File "/content/DeepFaceLab/core/interact/interact.py", line 8, in <module>
    import colorama
ModuleNotFoundError: No module named 'colorama'

**Comment by Orchoidizer** [comment]
Seems to have been sorted out now with the 'unfreeze DFL version' action by @chervonij 

I assume it was connected to that.
