### ISSUE TITLE
Unable to Extract or Train 

### ISSUE THREAD

**Issue by fulanito3030** [chervonij/DFL-Colab#54]
Hi,

There seems to be an error with DFL and Colab. When I attempt to extract frames and/or train. I get the following error:

RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Process Process-1:
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

SystemError: <built-in method __contains__ of dict object at 0x7f12a8ca95f0> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/content/DeepFaceLab/core/leras/device.py", line 102, in _get_tf_devices_proc
    import tensorflow
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/context.py", line 35, in <module>
    from tensorflow.python.client import pywrap_tf_session
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/pywrap_tf_session.py", line 19, in <module>
    from tensorflow.python.client._pywrap_tf_session import *
ImportError: initialization failed
Traceback (most recent call last):
  File "DeepFaceLab/main.py", line 7, in <module>
    nn.initialize_main_env()
  File "/content/DeepFaceLab/core/leras/nn.py", line 131, in initialize_main_env
    Devices.initialize_main_env()
  File "/content/DeepFaceLab/core/leras/device.py", line 174, in initialize_main_env
    visible_devices = q.get()
  File "/usr/lib/python3.7/multiprocessing/queues.py", line 94, in get
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)

I have attached a screenshot of the issue too. Thank you for all your hard work!!
<img width="1043" alt="Screen Shot 2022-10-12 at 2 57 45 PM" src="https://user-images.githubusercontent.com/99452881/195469295-a4bd1edd-4f8b-4efe-bb68-61add3f2b993.png">

**Comment by chervonij** [comment]
Issue not relevant.
Bug fixed long ago.
