### ISSUE TITLE
Error when training

### ISSUE THREAD

**Issue by Skierman** [chervonij/DFL-Colab#7]
Error: integer division or modulo by zero
Traceback (most recent call last):
  File "/content/DeepFaceLab/mainscripts/Trainer.py", line 49, in trainerThread
    device_args=device_args)
  File "/content/DeepFaceLab/models/ModelBase.py", line 230, in __init__
    self.sample_for_preview = self.generate_next_sample()
  File "/content/DeepFaceLab/models/ModelBase.py", line 467, in generate_next_sample
    return [next(generator) for generator in self.generator_list]
  File "/content/DeepFaceLab/models/ModelBase.py", line 467, in <listcomp>
    return [next(generator) for generator in self.generator_list]
  File "/content/DeepFaceLab/samplelib/SampleGeneratorFace.py", line 58, in __next__
    generator = self.generators[self.generator_counter % len(self.generators) ]
ZeroDivisionError: integer division or modulo by zero
Done.
/usr/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))

**Comment by chervonij** [comment]
It's not DFL-Colab error.
Try to check your datasets. I think they were deleted.

**Comment by Skierman** [comment]
How do I add my dataset? I can I just use the workspace folder from the windows prebuilt version uploaded to google drive?

**Comment by chervonij** [comment]
Tutorial is here:
https://mrdeepfakes.com/forums/thread-deepfacelab-google-colab-tutorial
